### ISSUE TITLE
steady-state

### ISSUE THREAD

**Issue by Mutaz94** [metrumresearchgroup/BayesPBPK-tutorial#1]
Hi Ahmed! 

Great work you did with this. I'm curious about the implementation of steady-state dosing in Turing/SciML. Have you looked into that? Thanks!! 

Mutaz

**Comment by aelmokadem** [comment]
Hi Mutaz,

There are steady state solvers implemented in SciML ecosystem but they are not really primed for handling the sort of multiple dosing that we often deal with. I did play with that a bit so we can talk through offline if you'd like.

Ahmed.
